task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 2 # your dataset classes
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /home2020/home/icube/keqichen/datasets/CrowdHuman/Images
    ann_file: /home2020/home/icube/keqichen/datasets/CrowdHuman/annotations/train_4dor7k_iter1_02.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /home2020/home/icube/keqichen/datasets/CrowdHuman/Images
    ann_file: /home2020/home/icube/keqichen/datasets/CrowdHuman/annotations/val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
